### PR TITLE
Byte stream should force binary encoding when 'valueEncoding' is set …

### PR DESCRIPTION
**Pull request by zacharygriffee**
Added a test as well.

fixes https://github.com/holepunchto/hypercore/issues/457#issue-1989192819

### CODE REVIEW

**Comment by mafintosh** [comment]
Some lint errors. Tried to fix some bug are on my phone

**Comment by zacharygriffee** [comment]
> Some lint errors. Tried to fix some bug are on my phone

Ooo. Sorry. I forgot to run the standard fixers. Working on it now.

**Comment by mafintosh** [comment]
Thanks!

**Comment by mafintosh** [comment]
Going out in next release

**Pull request merged**
