### PR TITLE
Use RAM in test: clear blocks with diff option

### PR DESCRIPTION
**Pull request by LuKks**
I thought it wasn't possible for it to return cleared bytes using RAM but seems possible by using a bigger buffer

### CODE REVIEW

**Comment by LuKks** [comment]
Ah I see here:
https://github.com/random-access-storage/random-access-memory/blob/52db73d55d3f4ed011a2b17abbe56fb7ac68be01/index.js#LL5C7-L5C24

**Comment by mafintosh** [comment]
cleaner to make it with an explicit page size imo

**Comment by mafintosh** [comment]
Just for this test

**Comment by LuKks** [comment]
@mafintosh Ready!

**Pull request merged**
